language: java
jdk:
 - oraclejdk8
# - openjdk8
before_install:
 - chmod +x gradlew
notifications:
  slack:
     rooms:
        - openbaton:0mU0eqEY8Dcm0sWeFiGrKvFe
     on_success: change
     on_failure: always
  email:
    - notifications@openbaton.org
cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle/wrapper/
script:
 - ./gradlew build
